version: "2"

services:
  webapp:
    build: ./webapp
    ports:
      - "80:5000"
    depends_on:
      - redis

  redis:
    image: redis

  worker:
    build: ./worker
    depends_on:
      - redis
